## What is PyTorch?
[Tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

In [1]:
import numpy as np
import torch

In [2]:
random_seed = 42
torch_random_seed = torch.manual_seed(random_seed)
np.random.seed(random_seed)

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 3.6893e+19, 1.3488e-20],
        [1.0845e-19, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[-1.2284,  0.5294,  1.2211],
        [ 0.1511, -0.3319, -0.4785],
        [-0.2631, -0.1786, -1.1859],
        [-0.8860, -0.7150,  0.1280],
        [-0.1603, -2.2161, -0.6858]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.6389,  1.2833,  1.4163],
        [ 0.1561, -0.0251, -0.3620],
        [ 0.6472,  0.4655, -0.4787],
        [-0.2279, -0.2237,  1.0193],
        [-0.0156, -1.6846, -0.5270]])


In [11]:
print(torch.add(x, y))

tensor([[-0.6389,  1.2833,  1.4163],
        [ 0.1561, -0.0251, -0.3620],
        [ 0.6472,  0.4655, -0.4787],
        [-0.2279, -0.2237,  1.0193],
        [-0.0156, -1.6846, -0.5270]])


In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.6389,  1.2833,  1.4163],
        [ 0.1561, -0.0251, -0.3620],
        [ 0.6472,  0.4655, -0.4787],
        [-0.2279, -0.2237,  1.0193],
        [-0.0156, -1.6846, -0.5270]])


In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.6389,  1.2833,  1.4163],
        [ 0.1561, -0.0251, -0.3620],
        [ 0.6472,  0.4655, -0.4787],
        [-0.2279, -0.2237,  1.0193],
        [-0.0156, -1.6846, -0.5270]])


In [14]:
print(x[:, 1])

tensor([ 0.5294, -0.3319, -0.1786, -0.7150, -2.2161])


In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3295])
-0.329508841038


In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!